### ISSUE TITLE
"Underlying prevalue editor isn't valid " when trying to login

### ISSUE THREAD

**Issue by Nikita-reddy** [abjerner/Skybrud.Social-for-Umbraco#1]
Hi Anders,
I was trying to setup the twitter authorize using Skyburd.Social and was getting the following error on clicking the authorize button:

"Hold on now! The options of the underlying prevalue editor isn't valid. "

I have set the Consumer Key and Consumer secret in the Datatype.

In the twitter apps setting  I have also setup the call back url.

Could not find where the problem is with.

After, looking at the source code ,I could be able to figure out why there was an issue with this.

In my document types I was setting the Twitter authorize on a Document type composition , instead of setting it directly on the Home Page.
As it was part of Document type Composition, it could not get the property type and its values .

The reason for this was :

In PreValueHelpers.cs : Skybrud.Social is trying to get the Property type as follows:

publicstaticIDictionary<string, string> GetPreValues(string contentTypeAlias, string propertyAlias) 
{ 
    IContentType contentType = ContentTypeService.GetContentType(contentTypeAlias);
   PropertyType property = contentType == null ? null : contentType.PropertyTypes.FirstOrDefault(x => x.Alias == propertyAlias);
 return property == null ? new Dictionary<string, string>() : GetPreValues(property.DataTypeDefinitionId);
}

By modifying above method  as follows fixes the issue.

publicstaticIDictionary<string, string> GetPreValues(string contentTypeAlias, string propertyAlias)
 {
     IContentType contentType = ContentTypeService.GetContentType(contentTypeAlias); 
    PropertyType property = contentType == null ? null : contentType.PropertyTypes.FirstOrDefault(x => x.Alias == propertyAlias); 
   if (property == null)
   {
     property = contentType.CompositionPropertyTypes.FirstOrDefault(x => x.Alias == propertyAlias);
   }
  return property == null ? newDictionary<string, string>() : GetPreValues (property.DataTypeDefinitionId);
}

Before Skybrud.Social was getting property type which was available only on Content type page directly.

Now, I have modified such that if the property type is returning null or empty then it gets the property type available on Document type Composition.

I have also put this fix on ourumbraco.org Forums,
Link: 
https://our.umbraco.org/projects/website-utilities/skybrudsocial-for-umbraco-7/general-discussion/64757-Problem-with-setting-up-the-Twitter-Authorize-using-SkyburdSocial?p=0#comment218960

Cheers,
Nikita

**Comment by abjerner** [comment]
Hi Nikita,

I hadn't tested the package with compositions, so thanks for finding the culprit.

I have now committed a fix based on your code: https://github.com/abjerner/Skybrud.Social.Umbraco/commit/4011bfbe40c07ad669c9366221bbae85be306489

(since this is actually the repository of the Umbraco 6 package, I'm closing the issue here)
